config/routes.rb
EducationAnalyticsGit01::Application.routes.draw do
  resources :painels

end

app/models/painel.rb
class Painel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/painels_controller.rb
class PainelsController < ApplicationController
  before_action :set_painel, only: [:show, :edit, :update, :destroy]

  # GET /painels
  # GET /painels.json
  def index
    @painels = Painel.all
  end

  # GET /painels/1
  # GET /painels/1.json
  def show
  end

  # GET /painels/new
  def new
    @painel = Painel.new
  end

  # GET /painels/1/edit
  def edit
  end

  # POST /painels
  # POST /painels.json
  def create
    @painel = Painel.new(painel_params)

    respond_to do |format|
      if @painel.save
        format.html { redirect_to @painel, notice: 'Painel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @painel }
      else
        format.html { render action: 'new' }
        format.json { render json: @painel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /painels/1
  # PATCH/PUT /painels/1.json
  def update
    respond_to do |format|
      if @painel.update(painel_params)
        format.html { redirect_to @painel, notice: 'Painel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @painel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /painels/1
  # DELETE /painels/1.json
  def destroy
    @painel.destroy
    respond_to do |format|
      format.html { redirect_to painels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painel
      @painel = Painel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painel_params
      params.require(:painel).permit(:nome_app, :tipo_evento, :qtd_evento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/painels_helper.rb
module PainelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EducationAnalyticsGit01</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/painels/_form.html.erb
<%= form_for(@painel) do |f| %>
  <% if @painel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painel.errors.count, "error") %> prohibited this painel from being saved:</h2>

      <ul>
      <% @painel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_app %><br>
    <%= f.text_field :nome_app %>
  </div>
  <div class="field">
    <%= f.label :tipo_evento %><br>
    <%= f.text_field :tipo_evento %>
  </div>
  <div class="field">
    <%= f.label :qtd_evento %><br>
    <%= f.text_field :qtd_evento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/painels/edit.html.erb
<h1>Editing painel</h1>

<%= render 'form' %>

<%= link_to 'Show', @painel %> |
<%= link_to 'Back', painels_path %>

app/views/painels/index.html.erb
<h1>Listing painels</h1>

<table>
  <thead>
    <tr>
      <th>Nome app</th>
      <th>Tipo evento</th>
      <th>Qtd evento</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @painels.each do |painel| %>
      <tr>
        <td><%= painel.nome_app %></td>
        <td><%= painel.tipo_evento %></td>
        <td><%= painel.qtd_evento %></td>
        <td><%= link_to 'Show', painel %></td>
        <td><%= link_to 'Edit', edit_painel_path(painel) %></td>
        <td><%= link_to 'Destroy', painel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Painel', new_painel_path %>

app/views/painels/new.html.erb
<h1>New painel</h1>

<%= render 'form' %>

<%= link_to 'Back', painels_path %>

app/views/painels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome app:</strong>
  <%= @painel.nome_app %>
</p>

<p>
  <strong>Tipo evento:</strong>
  <%= @painel.tipo_evento %>
</p>

<p>
  <strong>Qtd evento:</strong>
  <%= @painel.qtd_evento %>
</p>

<%= link_to 'Edit', edit_painel_path(@painel) %> |
<%= link_to 'Back', painels_path %>